### ISSUE TITLE
dkms and MODULE_VERSION

### ISSUE THREAD

**Issue by celane** [dpenkler/linux-usbtmc#6]
Well, the dkms code got changed a few week back, and a lot of module code started throwing errors on kernel updates. 

Turns out, modules *should* have a something like
MODULE_VERSION("1.4") 
in the source, but no one seems to have noticed (because there were no errors?) 

IMO, it really is needed for DAQ-related modules, because some interfaces will work for particular versions, and you can't exactly run them with "--version". 

So, forked, put in the MODULE_VERSION, and a bunch of other 'packaging' stuff to generate rpms for dkms installs.  Take a look, see if there's anything you want.

**Comment by dpenkler** [comment]
Added MODULE_VERSION(USBTMC_VERSION)
